INSERT INTO tbl_doibong (ten_doi, quoc_gia) VALUES 
('Arsenal', 'Anh'),
('Aston Villa', 'Anh'),
('Bournemouth', 'Anh'),
('Brentford', 'Anh'),
('Brighton & Hove Albion', 'Anh'),
('Chelsea', 'Anh'),
('Crystal Palace', 'Anh'),
('Everton', 'Anh'),
('Fulham', 'Anh'),
('Ipswich Town', 'Anh'),
('Leicester City', 'Anh'),
('Liverpool', 'Anh'),
('Manchester City', 'Anh'),
('Manchester United', 'Anh'),
('Newcastle United', 'Anh'),
('Nottingham Forest', 'Anh'),
('Southampton', 'Anh'),
('Tottenham Hotspur', 'Anh'),
('West Ham United', 'Anh'),
('Wolverhampton Wanderers', 'Anh');